---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-server-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgA85S58DUuqJqsd8qj6Ypg3jhwTTVfvlE+He+NkF9K+JRZkpljdWOdCyjFyJgADFl6RNL8bF59/bvooVg6NtI+ry2PNY3Mma+PMU1qlCxa8uEbrsw0rgPfaUPwsreyuDJc5FF9qm6iSjbyu514So+1E5mXOyDRS/92ITWicp9423f/B1HBk+91dSFk45af2lbSst1nKrF2zDmVQlFgv7eFKvPWR1UAQUmYoYKn+qkCsBLhPi6uvsbYFErwFOuR1DRE3FSpRv3UggBfmFhwn7teGrzSdYJTkiqXyizxOpWjBrHUtPHM6xq3qaJhAwJhlqDZnNY9OxOBdiPV5IwfnJvauQFOSnjZVLH3JLbknq02sLHEIzw0FUuaLkYB1TcATQjl/bxZ+IeJ1spNM8bo+zPcoTUcKpNpDjnxzueqqUS3RlrBFYiKRNQodfNPsozB0pHqwLJ/BOj/z2OdecR2OEQoxvOJNe8KS0lyjD5skeO6fKdr75OFFC2I1SVKkxDPAXbugNroV4NWGfboxmasYdf/kMc0FdzHxw6TF0CQFfGS9FOw65dS6f2S+R9DuyCwsRjUY1mdH0Hn2R3RUdW0+eOfBlICHSN6ER6TctrqOo2t572HIm5ye09FAVK0TCT/xjOtkfhIyVlTYKlYZO2SsShNFG8Q0luIlHdEZ+8s92555TsPcPhv2jmU7KmtRAgcbtthfD1CyHOJ8KujYhFEZkVC266m6WoPkuLexCY/U39MSl7BkFnc=
    client-secret: AgA+jEP4oP4TFi8zDVolOugZsUGjAsYpBWvvKDbsCZPBYFXbXBLT6DoPAKybLBisk5uUDhEs4SOsgqgUDNXVlLNXMM3W8VfHEgUXWM+x93GJb189qkwl7e+tWPM4F6NrW0HT0R8QLKD/0WZg7I1uWNG9Wak6snA7AYx2NkMa6LhcPBWa2OQ8mNHqTsikjVCe5nPqGh6gbfVQf7qPT3Ob5ApDge+6c17pZJTxocKqAJ+y6m0njc+pinNYazM3dCeyFSvEPt15LVYNWgmGsTofydeyrVK/MMEXFF8FGbgaaoh9grWUL63+9tWT7K6A4DzjMfEz5i2a/o7WxF53LsS2Jz4c+HIEzUm7Xb6BkJwK4h/pc7FQ9K0XlKsSliezxhY+BfkG2f9EXpb0QI+WPrli3Kj/foYC6wH4G6cTqZ1iM+Y8GdrS+a/mjcL3f4oNdU4CfJ7XGa/DsUv9cie3aNAeI+sB7fa92EK5+ZQZPdYnBkCdM6wqGTKmHccuqXFOwxAxdEQGsEtcTcXh+v7IGfG9v1KNAzvzDNM3zluq+eCxlUhmdw+GUPw583ENmyGFtXwg4REKf+yG27IULjd7rMw92x5k8rO0v67FKPUXCMrdBRVoM0G5isIBgCNzofGwewnzNPgxtXgsaPkKWXrtCLHsOUhxEnby6g6UFCrdyUPswry+ehxN6xN+hdoG5C97I2Ax5aSS3Xa1XOROoxdGm67oGITbDr4mRNgUYNtiLTdPU7opwSNDMOKYjWAo
  template:
    metadata:
      creationTimestamp: null
      name: argo-server-sso
      namespace: argo
